force-app/main/default/objects/Milestone__c/Milestone__c.object-meta.xml
<CustomObject>
    <label>Milestone</label>
    <nameField>
        <label>Milestone Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Milestones</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Milestone__c/fields/Completion__c.field-meta.xml
<CustomField>
    <fullName>Completion__c</fullName>
    <formula>BLANKVALUE((CompletedToDoItemsRelated__c  /  ToDoItemsRelated__c) , 0)</formula>
    <label>Completion</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Milestone__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <description>Related project.</description>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Milestones</relationshipLabel>
    <relationshipName>Milestones</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Milestone__c/fields/ToDoItemsRelated__c.field-meta.xml
<CustomField>
    <fullName>ToDoItemsRelated__c</fullName>
    <description>Number of to-do items related to the milestone.</description>
    <inlineHelpText>Number of to-do items related to the milestone.</inlineHelpText>
    <label>To-Do items</label>
    <summaryForeignKey>ToDoItem__c.Milestone__c</summaryForeignKey>
    <summaryOperation>count</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Project__c/fields/Completion__c.field-meta.xml
<CustomField>
    <fullName>Completion__c</fullName>
    <formula>IF( NOT(ISBLANK(TotalCompletedMilestones__c)) &amp;&amp; NOT(ISBLANK(TotalMilestones__c)), TotalCompletedMilestones__c / TotalMilestones__c, 0)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Completion</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/classes/ProjectManagerMilestonesListController.cls
public with sharing class ProjectManagerMilestonesListController {

    @AuraEnabled
    public static List<Milestone__c> getMilestonesByParentId(String parentId){
        try {
            return [
                SELECT Id, Name, ToDoItemsRelated__c, Completion__c
                FROM Milestone__c 
                WHERE Project__c =: parentId
            ];
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }

    // A Boolean value that is set to true if the DML operation was successful for this object, false otherwise.
    @AuraEnabled
    public static Boolean deleteItem(String recordId){
        return Utils.deleteItem(new Milestone__c(Id = recordId))
    }
}