force-app/main/default/objects/Milestone__c/Milestone__c.object-meta.xml
<CustomObject>
    <label>Milestone</label>
    <nameField>
        <label>Milestone Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Milestones</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Milestone__c/fields/EndDate__c.field-meta.xml
<CustomField>
    <fullName>EndDate__c</fullName>
    <label>End date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Milestone__c/fields/StartDate__c.field-meta.xml
<CustomField>
    <fullName>StartDate__c</fullName>
    <label>Start date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Milestone__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <formula>IF(CompletedToDoItemsRelated__c == 0, &quot;Not Started&quot;,
  IF(CompletedToDoItemsRelated__c == ToDoItemsRelated__c, &quot;Complete&quot;, &quot;In Progress&quot;))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Status</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ToDoItem__c/ToDoItem__c.object-meta.xml
<CustomObject>
    <label>To-Do Item</label>
    <nameField>
        <label>To-Do</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>To-Do Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/ToDoItem__c/fields/AssignedTo__c.field-meta.xml
<CustomField>
    <fullName>AssignedTo__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Field for assigning the user who performed the task.</description>
    <inlineHelpText>Field for assigning the user who performed the task.</inlineHelpText>
    <label>Assigned to</label>
    <referenceTo>User</referenceTo>
    <relationshipName>ToDoItems</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ToDoItem__c/fields/EndDate__c.field-meta.xml
<CustomField>
    <fullName>EndDate__c</fullName>
    <description>Task end date.</description>
    <inlineHelpText>Task end date.</inlineHelpText>
    <label>End date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/ToDoItem__c/fields/Milestone__c.field-meta.xml
<CustomField>
    <fullName>Milestone__c</fullName>
    <description>Related milestone.</description>
    <label>Milestone</label>
    <referenceTo>Milestone__c</referenceTo>
    <relationshipName>MilestoneTasks</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/ToDoItem__c/fields/StartDate__c.field-meta.xml
<CustomField>
    <fullName>StartDate__c</fullName>
    <description>Task start date.</description>
    <inlineHelpText>Task start date.</inlineHelpText>
    <label>Start date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/ToDoItem__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Field to inform the status of the task</description>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>ProjectStatus</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/ProjectStatus.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Not Started</fullName>
        <default>true</default>
        <label>Not Started</label>
    </customValue>
    <customValue>
        <fullName>In Progress</fullName>
    </customValue>
    <customValue>
        <fullName>Complete</fullName>
    </customValue>
    <masterLabel>Project Status</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/ProjectManagerToDoListController.cls
public with sharing class ProjectManagerToDoListController {

    @AuraEnabled(cacheable=true)
    public static List<ToDoItem__c> getToDoItemsByParentId( String parentId){
        try {
            return [
                SELECT Id, Name, Status__c, AssignedTo__r.Name, StartDate__c, EndDate__c
                FROM ToDoItem__c
                WHERE Milestone__c =: parentId
                WITH SECURITY_ENFORCED
            ];
            
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }

    // A Boolean value that is set to true if the DML operation was successful for this object, false otherwise.
    @AuraEnabled
    public static Boolean deleteItem(String recordId){
        return Utils.deleteItem(new ToDoItem__c(Id = recordId));
    }
}