force-app/main/default/objects/Milestone__c/Milestone__c.object-meta.xml
<CustomObject>
    <label>Milestone</label>
    <nameField>
        <label>Milestone Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Milestones</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Milestone__c/fields/EndDate__c.field-meta.xml
<CustomField>
    <fullName>EndDate__c</fullName>
    <label>End date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Milestone__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <description>Related project.</description>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Milestones</relationshipLabel>
    <relationshipName>Milestones</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Milestone__c/fields/StartDate__c.field-meta.xml
<CustomField>
    <fullName>StartDate__c</fullName>
    <label>Start date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Milestone__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <formula>IF(CompletedToDoItemsRelated__c == 0, &quot;Not Started&quot;,
  IF(CompletedToDoItemsRelated__c == ToDoItemsRelated__c, &quot;Complete&quot;, &quot;In Progress&quot;))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Status</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Project__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <formula>IF(TotalCompletedMilestones__c  == 0, &quot;Not Started&quot;,
IF(TotalCompletedMilestones__c == TotalMilestones__c, &quot;Complete&quot;, &quot;In Progress&quot;))</formula>
    <label>Status</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ToDoItem__c/ToDoItem__c.object-meta.xml
<CustomObject>
    <label>To-Do Item</label>
    <nameField>
        <label>To-Do</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>To-Do Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/ToDoItem__c/fields/AssignedTo__c.field-meta.xml
<CustomField>
    <fullName>AssignedTo__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Field for assigning the user who performed the task.</description>
    <inlineHelpText>Field for assigning the user who performed the task.</inlineHelpText>
    <label>Assigned to</label>
    <referenceTo>User</referenceTo>
    <relationshipName>ToDoItems</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ToDoItem__c/fields/EndDate__c.field-meta.xml
<CustomField>
    <fullName>EndDate__c</fullName>
    <description>Task end date.</description>
    <inlineHelpText>Task end date.</inlineHelpText>
    <label>End date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/ToDoItem__c/fields/Milestone__c.field-meta.xml
<CustomField>
    <fullName>Milestone__c</fullName>
    <description>Related milestone.</description>
    <label>Milestone</label>
    <referenceTo>Milestone__c</referenceTo>
    <relationshipName>MilestoneTasks</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/ToDoItem__c/fields/StartDate__c.field-meta.xml
<CustomField>
    <fullName>StartDate__c</fullName>
    <description>Task start date.</description>
    <inlineHelpText>Task start date.</inlineHelpText>
    <label>Start date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/ToDoItem__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Field to inform the status of the task</description>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>ProjectStatus</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/ProjectStatus.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Not Started</fullName>
        <default>true</default>
        <label>Not Started</label>
    </customValue>
    <customValue>
        <fullName>In Progress</fullName>
    </customValue>
    <customValue>
        <fullName>Complete</fullName>
    </customValue>
    <masterLabel>Project Status</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/ProjectManagerToDoListControllerTest.cls
@isTest
private class ProjectManagerToDoListControllerTest {

    // Test setup is a good practice in test classes, to reuse the generated test content.
    @TestSetup
    static void makeData(){
        Project__c project = new Project__c( Name = 'Test Project' );
        insert project;

        Milestone__c milestone = new Milestone__c( 
            Name = 'Test Milestone',
            Project__c = project.id,
            StartDate__c = Date.today(),
            EndDate__c = Date.today().addDays(7)
        );
        insert milestone;
    }

    // Call the controller method to search for the parent milestone by ID and check if the record was inserted.
    @isTest
    static void testGetToDoItemsByParentId() {
        Milestone__c milestone = [SELECT Id FROM Milestone__c WHERE Name =  'Test Milestone'];

        ToDoItem__c todoItem = new ToDoItem__c(
            Name = 'Test ToDo',
            Status__c = 'In Progress',
            AssignedTo__c = UserInfo.getUserId(),
            StartDate__c = Date.today(),
            EndDate__c = Date.today().addDays(7),
            Milestone__c = milestone.Id
        );
        insert todoItem;

        List<ToDoItem__c> todoItems = ProjectManagerToDoListController.getToDoItemsByParentId(milestone.Id);

        System.assertEquals(1, todoItems.size());
        System.assertEquals('Test ToDo', todoItems[0].Name);
    }

     // Calls the controller method to delete the record and checks whether the record was deleted.
    @isTest
    static void testDeleteItem() {
        Milestone__c milestone = [SELECT Id FROM Milestone__c WHERE Name =  'Test Milestone'];
    
        ToDoItem__c todoItem = new ToDoItem__c(
            Name = 'To Be Deleted',
            Status__c = 'In Progress',
            StartDate__c = Date.today(),
            EndDate__c = Date.today().addDays(7),
            Milestone__c = milestone.Id
        );
        insert todoItem;

        Boolean deleteResult = ProjectManagerToDoListController.deleteItem(todoItem.Id);

        System.assertEquals(true, deleteResult);

        List<ToDoItem__c> todoItemsAfterDelete = [SELECT Id FROM ToDoItem__c WHERE Id = :todoItem.Id];
        System.assertEquals(0, todoItemsAfterDelete.size());
    }
}