force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Project__c/fields/Completion__c.field-meta.xml
<CustomField>
    <fullName>Completion__c</fullName>
    <formula>IF( NOT(ISBLANK(TotalCompletedMilestones__c)) &amp;&amp; NOT(ISBLANK(TotalMilestones__c)), TotalCompletedMilestones__c / TotalMilestones__c, 0)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Completion</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Project__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <formula>IF(TotalCompletedMilestones__c  == 0, &quot;Not Started&quot;,
IF(TotalCompletedMilestones__c == TotalMilestones__c, &quot;Complete&quot;, &quot;In Progress&quot;))</formula>
    <label>Status</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ProjectManagerAppMessage__mdt/ProjectManagerAppMessage__mdt.object-meta.xml
<CustomObject>
    <description>Custom metadata type referring to the messages displayed in the components.</description>
    <label>Project Manager Message</label>
    <pluralLabel>Project Manager Messages</pluralLabel>
</CustomObject>

force-app/main/default/classes/ProjectManagerParentController.cls
public with sharing class ProjectManagerParentController {
    
    @AuraEnabled
    public static Map<String, ProjectManagerAppMessage__mdt> getProjectManagerAppMessageMDT(){
        try {
            return ProjectManagerAppMessage__mdt.getAll();
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }

    @AuraEnabled
    public static List<Project__c> getProjectById(String recordId){
        try {
            return [
                SELECT Id, Name, Completion__c, CreatedDate, Status__c
                FROM Project__c
                WHERE Id =: recordId
            ];
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }

    // A Boolean value that is set to true if the DML operation was successful for this object, false otherwise.
    @AuraEnabled
    public static Boolean deleteItem(String recordId){
        Database.DeleteResult dr = Database.delete(new Project__c(Id = recordId));
        return dr.isSuccess();
    }
}